Feature/iot_1228_multicast_docs
OS2iot/OS2IoT-docs pull request #19
Opened 2021-12-16 13:59 UTC by augusthjerrild

Documentation for multicast-groups in OS2IoT.

2022-01-25 09:04 UTC, AramAlsabti requested changes

2022-01-25 09:04 UTC, AramAlsabti commented on source/multicast/multicast.rst
> +The multicast-address has to be a 8-char hex value, and the network and application session key has to be a 32-char hex value.
"Hex" hasn't been mentioned in any of the other pages. So, for the first-time use, let's make it clear what the abbreviation is of like so:

"The multicast-address has to be an 8-character hexadecimal (hex) value (...)".
Now, we've established the shorthand form to the reader. We're free to use it for the remainder of this page.

2022-01-26 10:27 UTC, augusthjerrild commented on source/multicast/multicast.rst
> +|image1|
Does not return anything.

2022-01-26 12:38 UTC, augusthjerrild commented on source/multicast/multicast.rst
> +|image1|
When PR is accepted, I will attach in the issue.

2022-01-26 12:44 UTC, AramAlsabti approved these changes
Minor feedback. Looks good to me

2022-01-26 12:44 UTC, AramAlsabti commented on source/multicast/multicast.rst
> +**Multicast address:** An address that defines the multicast-group. Has to be a 8-character hex value.
"(...) **an** 8-character (...)"

2022-01-26 12:44 UTC, AramAlsabti commented on source/multicast/multicast.rst
> +When the multicast-group is created it's possible to send a downlink payload to the group of devices. This is done by navigating to the details-page of the multicast-group, and from here you have to
Details page is two words and without a hyphen

2022-01-26 12:48 UTC, merged